### ISSUE TITLE
Les messages ne sont pas disponibles sur la version mobile

### ISSUE THREAD

**Issue by c-geek** [duniter-gchange/gchange-client#32]
Je devais faire un échange avec Gaëlle, et je me suis fait avoir par le système de notifications qui ne m'indiquait pas les nouveaux messages. Voici la situation : 

* je rédige mon offre sur www.gchange.fr dans mon navigateur de ma machine de bureau
* Gaëlle et moi entrons en contact par les commentaires d'annonce, puis je décide de passer par les MP pour nous donner rendez-vous, toujours sur ma machine de bureau
* nous échangeons quelques messages, mais sans nous accorder précisément sur l'heure et le lieu de RDV
* j'attends sa confirmation ... en regardant mes notifications sur l'application gchange mobile (Google Play, v0.5.7). Mais je ne reçois rien. J'ai pourtant tout activé sur l'application mobile.

Étonné de ne pas avoir eu de réponse, je regarde ce matin sur ma machine de bureau : Gaëlle m'avait bien envoyé de MP ! Mais je n'ai pas eu de notification sur mon mobile, même en cliquant sur "Voir tout". D'ailleurs c'est pareil sur la version web sur desktop, mais on dispose en plus de l'icône de messagerie que je n'ai pas sur mobile. Alors je pensais quand même être notifié de mon message perso, j'aurais certainement réagi en voyant une notif sans pouvoir accéder à son contenu.

Bref ... voilà un piège dans lequel je suis tombé, peut-être d'autres se feront-ils avoir.

**Comment by blavenie** [comment]
erreur côté gchange-pod : 
```
[2017-09-26 02:24:25,447][ERROR][org.duniter.elasticsearch.service.changes.ChangeService] Failed to send message
java.lang.NullPointerException
        at org.duniter.elasticsearch.websocket.WebSocketChangesEndPoint.onChange(WebSocketChangesEndPoint.java:94)
        at org.duniter.elasticsearch.service.changes.ChangeService$1$1.addChange(ChangeService.java:177)
        at org.duniter.elasticsearch.service.changes.ChangeService$1$1.postIndex(ChangeService.java:145)
        at org.elasticsearch.index.indexing.ShardIndexingService.postIndex(ShardIndexingService.java:171)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:611)
        at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2017-09-26 02:46:05,797][ERROR][org.duniter.elasticsearch.service.changes.ChangeService] Failed to send message
```

**Comment by Pafzedog** [comment]
Je confirme, il n'y a pas d’icône "messages" sur la version Android et impossible de voir les messages échangés.

**Comment by webafrancois** [comment]
Ce n'est pas tout a fait le problème. On ne voit pas l'icone en dessous d'une largeur de résolution de 992 pixels.
Même sur un écran de PC.
D'ailleurs l'aspect du site change à ce moment-là : 
![larg991-gchange](https://user-images.githubusercontent.com/19719849/53126943-976b4400-3561-11e9-8372-a335641362cc.png)

![large992-gchange](https://user-images.githubusercontent.com/19719849/53126982-ace06e00-3561-11e9-9a47-3108f20434e5.png)

**Comment by blavenie** [comment]
Corrigé en v0.9.1
